---------------------
------- Ville -------
---------------------
INSERT INTO Ville (ville) VALUES ('dï¿½sseldorf');
INSERT INTO Ville (ville) VALUES ('rivello');
INSERT INTO Ville (ville) VALUES ('uitbergen');
INSERT INTO Ville (ville) VALUES ('buken');
INSERT INTO Ville (ville) VALUES ('adrano');
INSERT INTO Ville (ville) VALUES ('monceau-sur-sambre');
INSERT INTO Ville (ville) VALUES ('muiden');
INSERT INTO Ville (ville) VALUES ('pettineo');
INSERT INTO Ville (ville) VALUES ('subbiano');
INSERT INTO Ville (ville) VALUES ('khammam');
INSERT INTO Ville (ville) VALUES ('san rafael');
INSERT INTO Ville (ville) VALUES ('motta camastra');
INSERT INTO Ville (ville) VALUES ('zwolle');
INSERT INTO Ville (ville) VALUES ('township of minden hills');
INSERT INTO Ville (ville) VALUES ('surat');
INSERT INTO Ville (ville) VALUES ('norwich');
INSERT INTO Ville (ville) VALUES ('jackson');
INSERT INTO Ville (ville) VALUES ('shreveport');
INSERT INTO Ville (ville) VALUES ('dieppe');
INSERT INTO Ville (ville) VALUES ('cirencester');
INSERT INTO Ville (ville) VALUES ('nocciano');
INSERT INTO Ville (ville) VALUES ('beausejour');
INSERT INTO Ville (ville) VALUES ('hekelgem');
INSERT INTO Ville (ville) VALUES ('bientina');
INSERT INTO Ville (ville) VALUES ('haverfordwest');
INSERT INTO Ville (ville) VALUES ('provost');
INSERT INTO Ville (ville) VALUES ('dannevirke');
INSERT INTO Ville (ville) VALUES ('linkhout');
INSERT INTO Ville (ville) VALUES ('stokkem');
INSERT INTO Ville (ville) VALUES ('mesa');
INSERT INTO Ville (ville) VALUES ('dipignano');
INSERT INTO Ville (ville) VALUES ('bridgeport');
INSERT INTO Ville (ville) VALUES ('sadiqabad');
INSERT INTO Ville (ville) VALUES ('llanidloes');
INSERT INTO Ville (ville) VALUES ('lochristi');
INSERT INTO Ville (ville) VALUES ('masullas');
INSERT INTO Ville (ville) VALUES ('imphal');
INSERT INTO Ville (ville) VALUES ('candidoni');
INSERT INTO Ville (ville) VALUES ('biercï¿½e');
INSERT INTO Ville (ville) VALUES ('weston-super-mare');
INSERT INTO Ville (ville) VALUES ('schleswig');
INSERT INTO Ville (ville) VALUES ('fort saskatchewan');
INSERT INTO Ville (ville) VALUES ('lanklaar');
INSERT INTO Ville (ville) VALUES ('matera');
INSERT INTO Ville (ville) VALUES ('loupoigne');
INSERT INTO Ville (ville) VALUES ('roccabruna');
INSERT INTO Ville (ville) VALUES ('sanluri');
INSERT INTO Ville (ville) VALUES ('kontich');
INSERT INTO Ville (ville) VALUES ('veere');
INSERT INTO Ville (ville) VALUES ('quï¿½bec city');
INSERT INTO Ville (ville) VALUES ('bridgend');
INSERT INTO Ville (ville) VALUES ('springfield');
INSERT INTO Ville (ville) VALUES ('cambridge bay');
INSERT INTO Ville (ville) VALUES ('kirkwall');
INSERT INTO Ville (ville) VALUES ('cap-saint-ignace');
INSERT INTO Ville (ville) VALUES ('pastena');
INSERT INTO Ville (ville) VALUES ('wells');
INSERT INTO Ville (ville) VALUES ('ramillies');
INSERT INTO Ville (ville) VALUES ('gloucester');
INSERT INTO Ville (ville) VALUES ('minitonas');
INSERT INTO Ville (ville) VALUES ('mï¿½nster');
INSERT INTO Ville (ville) VALUES ('sainte-marie-chevigny');
INSERT INTO Ville (ville) VALUES ('rockingham');
INSERT INTO Ville (ville) VALUES ('olympia');
INSERT INTO Ville (ville) VALUES ('villamassargia');
INSERT INTO Ville (ville) VALUES ('san marcello');
INSERT INTO Ville (ville) VALUES ('barrow-in-furness');
INSERT INTO Ville (ville) VALUES ('alphen aan den rijn');
INSERT INTO Ville (ville) VALUES ('redcliffe');
INSERT INTO Ville (ville) VALUES ('episcopia');
INSERT INTO Ville (ville) VALUES ('dumbarton');
INSERT INTO Ville (ville) VALUES ('neunkirchen');
INSERT INTO Ville (ville) VALUES ('kalyan');
INSERT INTO Ville (ville) VALUES ('buzet');
INSERT INTO Ville (ville) VALUES ('sprimont');
INSERT INTO Ville (ville) VALUES ('balclutha');
INSERT INTO Ville (ville) VALUES ('offenburg');
INSERT INTO Ville (ville) VALUES ('colwood');
INSERT INTO Ville (ville) VALUES ('york');
INSERT INTO Ville (ville) VALUES ('pessac');
INSERT INTO Ville (ville) VALUES ('saint louis');
INSERT INTO Ville (ville) VALUES ('bally');
INSERT INTO Ville (ville) VALUES ('wrigley');
INSERT INTO Ville (ville) VALUES ('oxford county');
INSERT INTO Ville (ville) VALUES ('gentinnes');
INSERT INTO Ville (ville) VALUES ('haguenau');
INSERT INTO Ville (ville) VALUES ('novo hamburgo');
INSERT INTO Ville (ville) VALUES ('beauvechain');
INSERT INTO Ville (ville) VALUES ('traralgon');
INSERT INTO Ville (ville) VALUES ('atlanta');
INSERT INTO Ville (ville) VALUES ('mayerthorpe');
INSERT INTO Ville (ville) VALUES ('san giovanni la punta');
INSERT INTO Ville (ville) VALUES ('herstal');
INSERT INTO Ville (ville) VALUES ('haut-ittre');
INSERT INTO Ville (ville) VALUES ('rothesay');
INSERT INTO Ville (ville) VALUES ('vitã³ria da conquista');
INSERT INTO Ville (ville) VALUES ('austin');
INSERT INTO Ville (ville) VALUES ('bowling green');
INSERT INTO Ville (ville) VALUES ('amqui');
INSERT INTO Ville (ville) VALUES ('strï¿½e');
INSERT INTO Ville (ville) VALUES ('londerzeel');
INSERT INTO Ville (ville) VALUES ('south portland');
INSERT INTO Ville (ville) VALUES ('valladolid');
INSERT INTO Ville (ville) VALUES ('balvano');
INSERT INTO Ville (ville) VALUES ('gladstone');
INSERT INTO Ville (ville) VALUES ('frankenthal');
INSERT INTO Ville (ville) VALUES ('gï¿½rlitz');
INSERT INTO Ville (ville) VALUES ('castel di tora');
INSERT INTO Ville (ville) VALUES ('purmerend');
INSERT INTO Ville (ville) VALUES ('sauveniï¿½re');
INSERT INTO Ville (ville) VALUES ('roosendaal');
INSERT INTO Ville (ville) VALUES ('hï¿½villers');
INSERT INTO Ville (ville) VALUES ('ligny');
INSERT INTO Ville (ville) VALUES ('bromyard');
INSERT INTO Ville (ville) VALUES ('crowsnest pass');
INSERT INTO Ville (ville) VALUES ('le petit-quevilly');
INSERT INTO Ville (ville) VALUES ('matagami');
INSERT INTO Ville (ville) VALUES ('telford');
INSERT INTO Ville (ville) VALUES ('oyen');
INSERT INTO Ville (ville) VALUES ('ravels');
INSERT INTO Ville (ville) VALUES ('glovertown');
INSERT INTO Ville (ville) VALUES ('kruibeke');
INSERT INTO Ville (ville) VALUES ('glasgow');
INSERT INTO Ville (ville) VALUES ('montese');
INSERT INTO Ville (ville) VALUES ('rosenheim');
INSERT INTO Ville (ville) VALUES ('minervino di lecce');
INSERT INTO Ville (ville) VALUES ('erpe');
INSERT INTO Ville (ville) VALUES ('thorembais-saint-trond');
INSERT INTO Ville (ville) VALUES ('st. albert');
INSERT INTO Ville (ville) VALUES ('melle');
INSERT INTO Ville (ville) VALUES ('pont-ï¿½-celles');
INSERT INTO Ville (ville) VALUES ('bathgate');
INSERT INTO Ville (ville) VALUES ('akron');
INSERT INTO Ville (ville) VALUES ('avignon');
INSERT INTO Ville (ville) VALUES ('profondeville');
INSERT INTO Ville (ville) VALUES ('asti');
INSERT INTO Ville (ville) VALUES ('orilla');
INSERT INTO Ville (ville) VALUES ('ofena');
INSERT INTO Ville (ville) VALUES ('livingston');
INSERT INTO Ville (ville) VALUES ('montignies-saint-christophe');
INSERT INTO Ville (ville) VALUES ('erquelinnes');
INSERT INTO Ville (ville) VALUES ('mundare');
INSERT INTO Ville (ville) VALUES ('meppel');
INSERT INTO Ville (ville) VALUES ('rocca d arazzo');
INSERT INTO Ville (ville) VALUES ('bayreuth');
INSERT INTO Ville (ville) VALUES ('caerphilly');
INSERT INTO Ville (ville) VALUES ('bevagna');
INSERT INTO Ville (ville) VALUES ('bitterfeld-wolfen');
INSERT INTO Ville (ville) VALUES ('worcester');
INSERT INTO Ville (ville) VALUES ('deerlijk');
INSERT INTO Ville (ville) VALUES ('westlock');
INSERT INTO Ville (ville) VALUES ('ramara');
INSERT INTO Ville (ville) VALUES ('salt lake city');
INSERT INTO Ville (ville) VALUES ('vihari');
INSERT INTO Ville (ville) VALUES ('san floriano del collio');
INSERT INTO Ville (ville) VALUES ('bunbury');
INSERT INTO Ville (ville) VALUES ('jamioulx');
INSERT INTO Ville (ville) VALUES ('tarbes');
INSERT INTO Ville (ville) VALUES ('koersel');
INSERT INTO Ville (ville) VALUES ('izel');
INSERT INTO Ville (ville) VALUES ('dhule');
INSERT INTO Ville (ville) VALUES ('cropalati');
INSERT INTO Ville (ville) VALUES ('sundrie');
INSERT INTO Ville (ville) VALUES ('montigny-lã¨s-metz');
INSERT INTO Ville (ville) VALUES ('glendon');
INSERT INTO Ville (ville) VALUES ('sunderland');
INSERT INTO Ville (ville) VALUES ('veldegem');
INSERT INTO Ville (ville) VALUES ('orroli');
INSERT INTO Ville (ville) VALUES ('zwevegem');
INSERT INTO Ville (ville) VALUES ('elsene');
INSERT INTO Ville (ville) VALUES ('harrison hot springs');
INSERT INTO Ville (ville) VALUES ('auvelais');
INSERT INTO Ville (ville) VALUES ('sachs harbour');
INSERT INTO Ville (ville) VALUES ('halifax');
INSERT INTO Ville (ville) VALUES ('knokke-heist');
INSERT INTO Ville (ville) VALUES ('sylvan lake');
INSERT INTO Ville (ville) VALUES ('montebelluna');
INSERT INTO Ville (ville) VALUES ('lavacherie');
INSERT INTO Ville (ville) VALUES ('maranello');
INSERT INTO Ville (ville) VALUES ('hofstade');
INSERT INTO Ville (ville) VALUES ('filot');
INSERT INTO Ville (ville) VALUES ('grumo appula');
INSERT INTO Ville (ville) VALUES ('redwater');
INSERT INTO Ville (ville) VALUES ('heusden');
INSERT INTO Ville (ville) VALUES ('sulzbach');
INSERT INTO Ville (ville) VALUES ('valleyview');
INSERT INTO Ville (ville) VALUES ('kakisa');
INSERT INTO Ville (ville) VALUES ('calco');
INSERT INTO Ville (ville) VALUES ('bouwel');
INSERT INTO Ville (ville) VALUES ('quimper');
INSERT INTO Ville (ville) VALUES ('mogi das cruzes');
INSERT INTO Ville (ville) VALUES ('middlesbrough');
INSERT INTO Ville (ville) VALUES ('filey');
INSERT INTO Ville (ville) VALUES ('lacombe county');
INSERT INTO Ville (ville) VALUES ('nieuwmunster');

-----------------------
------- ADRESSE -------
-----------------------
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Macao','34367','amqui','Appartement 659-8204 Velit Route',13);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Poland','10790','strï¿½e','Id Route',240);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Costa Rica','54484','londerzeel','Aliquam Rue',155);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Jersey','8488XT','south portland','Ut Av.',157);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Latvia','8342MP','valladolid','Dictum Avenue',213);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Argentina','82588-306','balvano','Sem Route',160);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Yemen','04762','gladstone','Nunc Ave',223);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Albania','865011','frankenthal','Sed Route',149);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Somalia','9362','gï¿½rlitz','Egestas. Ave',66);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Australia','3870AI','castel di tora','Orci. Chemin',111);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Ecuador','64514','purmerend','Euismod Impasse',298);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Azerbaijan','5288','sauveniï¿½re','Pharetra Avenue',154);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Lebanon','5816','roosendaal','Scelerisque Rd.',152);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Tuvalu','5946','hï¿½villers','Sed Route',135);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Northern Mariana Islands','1829','ligny','Mauris Route',232);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Israel','25221','bromyard','Varius Rd.',156);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('French Polynesia','5951','crowsnest pass','Libero Chemin',46);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Portugal','4349','le petit-quevilly','Diam Ave',237);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Montserrat','3837','matagami','Sem Rue',73);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Lithuania','66378','telford','Vulputate, Av.',34);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Greenland','56945','oyen','Lobortis Ave',293);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Georgia','0950','ravels','Tellus Route',203);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('New Caledonia','9437','glovertown','Magna. Chemin',274);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Libya','5881','kruibeke','Integer Rd.',240);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Sierra Leone','G6 2FU','glasgow','Cursus Av.',199);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Palau','1139','montese','Tincidunt Route',122);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('South Sudan','54883','rosenheim','Proin Chemin',276);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Libya','61648','minervino di lecce','Diam Avenue',285);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Tunisia','8397','erpe','Sit Ave',27);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Kyrgyzstan','P04 3LI','thorembais-saint-trond','Purus Route',201);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Equatorial Guinea','2542YN','st. albert','Pede. Av.',280);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Barbados','01813','melle','Molestie Impasse',157);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Korea, North','746514','pont-ï¿½-celles','Blandit. Rd.',109);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Mongolia','5661','bathgate','Malesuada Rd.',216);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Malta','7983LG','akron','Amet Rd.',46);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('United States Minor Outlying Islands','9108','avignon','Sagittis. Rue',17);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Liechtenstein','38400','profondeville','Tellus. Impasse',239);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Qatar','02130','asti','At, Ave',264);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Reunion','31540-360','orilla','Ante Ave',261);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Sao Tome and Principe','500431','ofena','Placerat Impasse',149);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Thailand','564716','livingston','Egestas Ave',132);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Egypt','84952','hekelgem','Mauris Avenue',89);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Senegal','59442','lacombe county','Sapien. Chemin',254);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bolivia','OX7 2ES','nieuwmunster','Sapien Av.',297);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Mexico','2855','lavacherie','Eleifend Impasse',214);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Mayotte','2985','montignies-saint-christophe','Eu Ave',32);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Guatemala','39901','erquelinnes','Egestas Rd.',121);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Belgium','W19 9PA','mundare','Orci. Chemin',199);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Turkey','36282','meppel','Luctus Avenue',77);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Hong Kong','30810','rocca d arazzo','Dapibus Route',266);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','750628','bayreuth','Mi. Chemin',54);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Slovenia','93769','caerphilly','Dapibus Chemin',67);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bolivia','31800','bevagna','Fringilla Av.',272);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bangladesh','8001AD','bitterfeld-wolfen','Non, Chemin',141);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Libya','84093','worcester','Magna. Rd.',277);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Monaco','7293','deerlijk','Adipiscing Impasse',239);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Ethiopia','54719','westlock','Malesuada. Ave',129);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Tajikistan','5207','ramara','Penatibus Impasse',15);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Botswana','62263','salt lake city','Feugiat Av.',221);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('French Polynesia','5285SN','vihari','Tristique Avenue',27);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Afghanistan','967853','san floriano del collio','Duis Av.',44);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Namibia','6637XJ','bunbury','Orci. Route',53);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Kyrgyzstan','7875','jamioulx','Non Rue',237);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Central African Republic','7262','san rafael','Et Impasse',135);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bangladesh','92540','tarbes','Etiam Rd.',24);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Uganda','09801','koersel','Ac Ave',45);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Kenya','985877','izel','Placerat, Av.',198);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Gambia','3692','dhule','Amet Av.',27);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Sudan','X6A 9P8','cropalati','Nibh Ave',155);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Cayman Islands','50867','sundrie','Laoreet Route',129);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Haiti','P2J 0N9','montigny-lã¨s-metz','Nisl Av.',288);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Botswana','85438','glendon','Parturient Rd.',247);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Oman','264761','sunderland','Ut Impasse',31);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Paraguay','479330','veldegem','Et Impasse',242);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Zimbabwe','28120-067','orroli','Nec Rue',281);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Equatorial Guinea','8905ZT','zwevegem','Neque Impasse',122);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bahrain','70323','elsene','Tincidunt. Ave',145);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Puerto Rico','09930','harrison hot springs','Nunc, Avenue',111);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Yemen','00967','auvelais','Nunc Ave',275);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Gambia','2341','sachs harbour','Mauris Route',159);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Mali','1398','halifax','Arcu. Impasse',261);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('French Polynesia','21103','knokke-heist','Blandit Chemin',9);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Kazakhstan','70136','sylvan lake','Donec Chemin',45);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Ãland Islands','79439','montebelluna','Aliquam Route',84);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Portugal','78935','lavacherie','Mi Rd.',209);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Samoa','99668','maranello','Dui Rue',42);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Hong Kong','03164','hofstade','Sed Rd.',213);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Algeria','174691','filot','Aliquam Av.',60);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Ethiopia','20165','grumo appula','Aliquam Rue',174);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Cape Verde','0826OJ','redwater','Cras Rue',294);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Cambodia','12470','heusden','Vel, Rd.',54);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Hungary','39105','sulzbach','Rhoncus. Rd.',257);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Nauru','36363-512','valleyview','Rutrum Chemin',77);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Cambodia','L6W 1J1','kakisa','Ac, Av.',185);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Turkmenistan','99747','calco','Nunc. Av.',212);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brazil','9988','bouwel','Placerat. Avenue',93);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Congo, the Democratic Republic of the','C7C 6SV','quimper','Ipsum Av.',139);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Czech Republic','40714','mogi das cruzes','Facilisis Rd.',179);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Niue','83146','middlesbrough','Mattis Impasse',167);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Zambia','H0A 3V7','filey','Arcu. Impasse',21);


----------------------------
--------- PERSONNE ---------
----------------------------
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Finn','Knox','Finn.Knox@gmail.com',20);
Insert INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Thaddeus','Christian','Thaddeus.Christian@hotmail.fr',31);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Alvin','Valentine','Alvin.Valentine@yahoo.fr',14);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Brynne','Price','Brynne.Price@gmail.com',48);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Caesar','Jackson','Caesar.Jackson.accumsan@hotmail.fr',82);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Barbara','Maxwell','Barbara@yahoo.fr',45);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Madison','Harmon','Madison.Harmon@gmail.com',58);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Malcolm','Sims','Malcolm.Sims@hotmail.fr',53);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Lawrence','Bean','Lawrence.Bean.et@yahoo.fr',35);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Margaret','Nielsen','Margaret.Nielsen@gmail.com',50);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Ocean','Fox','Ocean.Fox.commodo@hotmail.fr',96);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Shaine','Byers','Shaine.Byers@yahoo.fr',100);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('India','Moses','India.Moses@gmail.com',10);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Kyle','Rich','Kyle.Rich@hotmail.fr',14);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Venus','Cortez','Venus.Cortez@yahoo.fr',39);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Joshua','Patton','Joshua.Patton.nulla@gmail.com',9);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Orson','Irwin','Orson.Irwin@hotmail.fr',98);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Caryn','Powers','Caryn.Powers@yahoo.fr',38);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Daria','Harding','Daria.Harding.luctus@augueeu.gmail.com',91);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Uta','Donovan','Uta.Donovan@hotmail.fr',35);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Amena','Kramer','Amena.Kramer@yahoo.fr',59);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Jena','Guthrie','Jena.Guthrie@gmail.com',54);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Isabelle','English','Isabelle.English@hotmail.fr',6);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Vladimir','Hodge','Vladimir.Hodge@yahoo.fr',26);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Andrew','Carey','Andrew.Carey@gmail.com',66);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Malcolm','Jenkins','Malcolm.Jenkins@hotmail.fr',42);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Yeo','Gibson','Yeo.Gibson@yahoo.fr',14);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Rhonda','Petersen','Rhonda.Petersen@gmail.com',71);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Clementine','Rosales','Clementine.Rosales@hotmail.fr',71);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Destiny','Petersen','Destiny.Petersen@yahoo.fr',9);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Bianca','Miranda','Bianca.Miranda@gmail.com',18);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Otto','Brown','Otto.Brown@hotmail.fr',50);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Jolie','Villarreal','Jolie.Villarreal@yahoo.fr',83);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Kieran','Massey','Kieran@gmail.com',94);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Connor','Bryan','Connor.Bryan@hotmail.fr',40);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Arden','Buckner','Arden.Buckner@yahoo.fr',59);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Ramona','Berg','Ramona.Berg@gmail.com',19);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Pandora','Nguyen','Pandora.Nguyen.eu@hotmail.fr',86);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Austin','Good','Austin.Good@yahoo.fr',39);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Ursula','Miller','Ursula.Miller@gmail.com',68);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Nita','Sampson','Nita.Sampson.Integer@hotmail.fr',89);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Ava','Walter','Ava.Walter@yahoo.fr',21);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Kareem','Colon','Kareem.Colon@gmail.com',44);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Lana','Hoover','Lana.Hoover@hotmail.fr',6);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Harlan','Austin','Harlan@yahoo.fr',92);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Brianna','Crosby','Brianna.Crosby.parturient@gmail.com',34);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Sheila','Gomez','Sheila@hotmail.fr',53);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Martin','Mcgowan','Martin.Mcgowan@yahoo.fr',98);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Curran','Fischer','Curran@gmail.com',45);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Petra','Roach','Petra@hotmail.fr',37);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Matthew','Cherry','Matthew.Cherry@yahoo.fr',11);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Blaine','Pitts','Blaine.Pitts@gmail.com',83);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Inez','Dunn','Inez.Dunn.lectus@hotmail.fr',3);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Fuller','Hendricks','Fuller.Hendricks.quam@yahoo.fr',7);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Odysseus','Mcclain','Odysseus.Mcclain.Duis@gmail.com',37);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Bree','Dale','Bree@hotmail.fr',7);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Cameron','Guy','Cameron@yahoo.fr',93);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Reuben','Bray','Reuben@gmail.com',93);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Ethan','Harmon','Ethan@hotmail.fr',96);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Demetria','Wright','Demetria.Wright.ipsum@gmail.com',93);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Rina','Ross','Rina@hotmail.fr',1);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Zephania','Dyer','Zephania.Dyer.fringilla@yahoo.fr',72);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Aretha','Justice','Aretha@gmail.com',30);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Leilani','Gilliam','Leilani@hotmail.fr',100);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Nita','Kirkland','Nita@yahoo.fr',83);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Tate','Rosa','Tate.Rosa@gmail.com',73);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('MacKenzie','Harris','MacKenzie@hotmail.fr',82);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Sybill','Reyes','Sybill.Reyes.vulputate@yahoo.fr',17);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Uma','Compton','Uma@gmail.com',72);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Mia','Saunders','Mia@hotmail.fr',5);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Simon','Chambers','Simon.Chambers@yahoo.fr',59);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Myra','Gallegos','Myra@gmail.com',59);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Bianca','Pearson','Bianca.Pearson@hotmail.fr',13);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Amy','Bean','Amy.Bean@yahoo.fr',38);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Channing','King','Channing.King@gmail.com',66);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Nita','Mcbride','Nita.Mcbride@hotmail.fr',50);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Leigh','Ortiz','Leigh.Ortiz@ipsum@gmail.com',43);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Isaiah','Mclaughlin','Isaiah@hotmail.fr',42);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Lev','Hood','Lev.Hood@yahoo.fr',82);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Angelica','Berger','Angelica@gmail.com',83);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Kim','Mathis','Kim@gmail.com',96);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Adrienne','Miller','Adrienne.Miller@hotmail.fr',63);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Rashad','French','Rashad.French@yahoo.fr',67);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Iona','Barrett','Iona.Barrett@gmail.com',75);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Yuli','Eaton','Yuli.Eaton.nonummy@hotmail.fr',57);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Chester','Franco','Chester.Franco@yahoo.fr',91);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Yuri','Norman','Yuri.Norman@gmail.com',16);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Linda','Wilkins','Linda@hotmail.fr',77);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Yoshio','Mcmillan','Yoshio.Mcmillan@yahoo.fr',90);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Judith','Vaughan','Judith.Vaughan@gmail.com',12);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Quinn','Haney','Quinn.Haney@hotmail.fr',10);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Dante','Knapp','Dante.Knapp@yahoo.fr',46);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Lewis','Ward','Lewis.Ward.orci@gmail.com',57);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Chantale','Crosby','Chantale.Crosby@hotmail.fr',91);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Denise','Reid','Denise.Reid.yahoo.fr',48);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Rafael','Steele','Rafael.Steele@gmail.com',78);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Illana','Warren','Illana.Warren@hotmail.fr',17);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Abra','Bates','Abra.Bates@yahoo.fr',28);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Michael','Wilder','Michael.Wilder@yahoo.fr',74);


---------------------
------ COMPTE -------
---------------------
INSERT INTO Compte (login,password,idPersonne) VALUES ('Nichole','SPW09JHJ6QE',56);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Burton','RKN47LKA5BT',74);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Reuben','NUQ17DUN3KZ',63);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Kevyn','KQD23DQV4RS',25);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Kasimir','POY61OTI8TF',64);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Aaron','QCX87SQJ7WX',86);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Yardley','ZVZ79ZPJ7WG',37);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Sacha','TOK69BAX4MJ',68);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Keith','BTV62GEF0ND',16);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Hayley','AJY17QWF7TW',21);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Jonas','AIP06DAV4HO',15);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Emma','HQM98FTF2LN',51);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Celeste','RJZ46PBT1NN',82);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Chastity','MMK15IMF1RZ',1);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Justin','PLV42TSG4TL',91);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Noel','SVN91FGQ3UJ',98);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Stacy','GFA86BMS9NJ',44);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Janna','KAZ74SPH7LP',28);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Ciara','UOU67QCG1CZ',20);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Yoshio','NRN22LLO3HH',17);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Laith','ENA75TPK3TB',2);



----------------------
------ LOGEMENT ------
----------------------
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',458,1,8016,1);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',713,7,1087,2);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',202,5,7003,3);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',275,8,4409,4);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',648,6,640,5);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',521,9,9577,6);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',194,9,3258,7);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',417,6,3068,8);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',965,2,735,9);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',319,4,3012,10);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',115,2,5472,11);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',987,10,5294,12);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Chambre',456,4,5141,13);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',377,6,8957,14);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',158,6,5376,15);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',406,3,9003,16);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',477,2,9582,17);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',986,1,9300,18);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',126,9,2241,19);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',513,10,1349,20);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',649,2,6149,21);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',451,6,3432,22);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',993,7,3144,23);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',532,7,8593,24);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',636,1,7315,25);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Chambre',835,5,506,26);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',449,3,6065,27);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',708,4,1747,28);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',330,8,8269,29);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',676,1,5225,30);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',817,2,4340,31);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',40,6,730,32);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',358,4,6785,33);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',94,3,5042,34);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',256,5,3781,35);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',164,1,6900,36);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',418,2,9395,37);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',583,1,6622,38);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',252,4,5402,39);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',792,3,1354,40);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',397,8,498,41);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',986,9,1727,42);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',869,9,7720,43);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Chambre',893,4,9149,44);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',815,1,6793,45);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',698,5,2082,46);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',393,4,9001,47);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',230,5,9531,48);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',619,8,2902,49);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',235,8,1634,50);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',925,4,2685,51);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',91,1,2371,52);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',239,2,5825,53);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',321,10,1659,54);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',597,4,9803,55);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',436,8,8298,56);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',192,4,9266,57);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',635,3,7096,58);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',894,7,7611,59);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',925,1,4659,60);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',556,8,3881,61);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',613,9,2285,62);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',507,1,3162,63);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',865,8,237,64);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',518,7,5573,65);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',402,8,3687,66);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',135,9,8795,67);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',36,3,5617,68);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',671,6,8440,69);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',604,4,1361,70);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',39,3,7911,71);

