---------------------
------- Ville -------
---------------------
INSERT INTO Ville(ville) VALUES ('abou dabi');
INSERT INTO Ville(ville) VALUES ('abuja');
INSERT INTO Ville(ville) VALUES ('accra');
INSERT INTO Ville(ville) VALUES ('achgabat');
INSERT INTO Ville(ville) VALUES ('addis-abeba');
INSERT INTO Ville(ville) VALUES ('alger');
INSERT INTO Ville(ville) VALUES ('amsterdam');
INSERT INTO Ville(ville) VALUES ('andorre-la-vieille');
INSERT INTO Ville(ville) VALUES ('ankara');
INSERT INTO Ville(ville) VALUES ('antananarivo');
INSERT INTO Ville(ville) VALUES ('asuncion');
INSERT INTO Ville(ville) VALUES ('athènes');
INSERT INTO Ville(ville) VALUES ('bagdad');
INSERT INTO Ville(ville) VALUES ('bakou');
INSERT INTO Ville(ville) VALUES ('bamako');
INSERT INTO Ville(ville) VALUES ('bandar');
INSERT INTO Ville(ville) VALUES ('bangkok');
INSERT INTO Ville(ville) VALUES ('bangui');
INSERT INTO Ville(ville) VALUES ('banjul');
INSERT INTO Ville(ville) VALUES ('belgrade');
INSERT INTO Ville(ville) VALUES ('belmopan');
INSERT INTO Ville(ville) VALUES ('berlin');
INSERT INTO Ville(ville) VALUES ('berne');
INSERT INTO Ville(ville) VALUES ('beyrouth');
INSERT INTO Ville(ville) VALUES ('bichkek');
INSERT INTO Ville(ville) VALUES ('bissau');
INSERT INTO Ville(ville) VALUES ('bogota');
INSERT INTO Ville(ville) VALUES ('bratislava');
INSERT INTO Ville(ville) VALUES ('brazzaville');
INSERT INTO Ville(ville) VALUES ('bridgetown');
INSERT INTO Ville(ville) VALUES ('bruxelles');
INSERT INTO Ville(ville) VALUES ('bucarest');
INSERT INTO Ville(ville) VALUES ('budapest');
INSERT INTO Ville(ville) VALUES ('buenos aires');
INSERT INTO Ville(ville) VALUES ('bujumbura');
INSERT INTO Ville(ville) VALUES ('le caire');
INSERT INTO Ville(ville) VALUES ('canberra');
INSERT INTO Ville(ville) VALUES ('caracas');
INSERT INTO Ville(ville) VALUES ('chisinau');
INSERT INTO Ville(ville) VALUES ('conakry');
INSERT INTO Ville(ville) VALUES ('copenhague');
INSERT INTO Ville(ville) VALUES ('dacca');
INSERT INTO Ville(ville) VALUES ('dakar');
INSERT INTO Ville(ville) VALUES ('damas');
INSERT INTO Ville(ville) VALUES ('dili');
INSERT INTO Ville(ville) VALUES ('doha');
INSERT INTO Ville(ville) VALUES ('douchanbé');
INSERT INTO Ville(ville) VALUES ('dublin');
INSERT INTO Ville(ville) VALUES ('erevan');
INSERT INTO Ville(ville) VALUES ('gaborone');
INSERT INTO Ville(ville) VALUES ('guatemala');
INSERT INTO Ville(ville) VALUES ('hamilton');
INSERT INTO Ville(ville) VALUES ('la havane');
INSERT INTO Ville(ville) VALUES ('helsinki');
INSERT INTO Ville(ville) VALUES ('honiara');
INSERT INTO Ville(ville) VALUES ('islamabad');
INSERT INTO Ville(ville) VALUES ('jakarta');
INSERT INTO Ville(ville) VALUES ('jérusalem');
INSERT INTO Ville(ville) VALUES ('kaboul');
INSERT INTO Ville(ville) VALUES ('kampala');
INSERT INTO Ville(ville) VALUES ('khartoum');
INSERT INTO Ville(ville) VALUES ('kiev');
INSERT INTO Ville(ville) VALUES ('kinshasa');
INSERT INTO Ville(ville) VALUES ('lima');
INSERT INTO Ville(ville) VALUES ('lisbonne');
INSERT INTO Ville(ville) VALUES ('ljubljana');
INSERT INTO Ville(ville) VALUES ('londres');
INSERT INTO Ville(ville) VALUES ('luanda');
INSERT INTO Ville(ville) VALUES ('luxembourg');
INSERT INTO Ville(ville) VALUES ('madrid');
INSERT INTO Ville(ville) VALUES ('managua');
INSERT INTO Ville(ville) VALUES ('manama');
INSERT INTO Ville(ville) VALUES ('mexico');
INSERT INTO Ville(ville) VALUES ('minsk');
INSERT INTO Ville(ville) VALUES ('monrovia');
INSERT INTO Ville(ville) VALUES ('montevideo');
INSERT INTO Ville(ville) VALUES ('moroni');
INSERT INTO Ville(ville) VALUES ('moscou');
INSERT INTO Ville(ville) VALUES ('nassau');
INSERT INTO Ville(ville) VALUES ('new delhi');
INSERT INTO Ville(ville) VALUES ('nicosie');
INSERT INTO Ville(ville) VALUES ('nouakchott');
INSERT INTO Ville(ville) VALUES ('oslo');
INSERT INTO Ville(ville) VALUES ('ottawa');
INSERT INTO Ville(ville) VALUES ('ouagadougou');
INSERT INTO Ville(ville) VALUES ('oulan-bator');
INSERT INTO Ville(ville) VALUES ('palikir');
INSERT INTO Ville(ville) VALUES ('panama');
INSERT INTO Ville(ville) VALUES ('paris');
INSERT INTO Ville(ville) VALUES ('la paz');
INSERT INTO Ville(ville) VALUES ('phnom penh');
INSERT INTO Ville(ville) VALUES ('port moresby');
INSERT INTO Ville(ville) VALUES ('port-au-prince');
INSERT INTO Ville(ville) VALUES ('prague');
INSERT INTO Ville(ville) VALUES ('praia');
INSERT INTO Ville(ville) VALUES ('pyongyang');
INSERT INTO Ville(ville) VALUES ('pékin');
INSERT INTO Ville(ville) VALUES ('reykjavik');
INSERT INTO Ville(ville) VALUES ('riga');
INSERT INTO Ville(ville) VALUES ('riyad');
INSERT INTO Ville(ville) VALUES ('rome');
INSERT INTO Ville(ville) VALUES ('rio de janeiro');
INSERT INTO Ville(ville) VALUES ('saint-domingue');
INSERT INTO Ville(ville) VALUES ('saint-georges');
INSERT INTO Ville(ville) VALUES ('san josé');
INSERT INTO Ville(ville) VALUES ('san salvador');
INSERT INTO Ville(ville) VALUES ('santiago');
INSERT INTO Ville(ville) VALUES ('sarajevo');
INSERT INTO Ville(ville) VALUES ('singapour');
INSERT INTO Ville(ville) VALUES ('skopje');
INSERT INTO Ville(ville) VALUES ('sofia');
INSERT INTO Ville(ville) VALUES ('stockholm');
INSERT INTO Ville(ville) VALUES ('suva');
INSERT INTO Ville(ville) VALUES ('séoul');
INSERT INTO Ville(ville) VALUES ('tachkent');
INSERT INTO Ville(ville) VALUES ('tallinn');
INSERT INTO Ville(ville) VALUES ('tegucigalpa');
INSERT INTO Ville(ville) VALUES ('thimphou');
INSERT INTO Ville(ville) VALUES ('tirana');
INSERT INTO Ville(ville) VALUES ('tokyo');
INSERT INTO Ville(ville) VALUES ('tripoli');
INSERT INTO Ville(ville) VALUES ('téhéran');
INSERT INTO Ville(ville) VALUES ('varsovie');
INSERT INTO Ville(ville) VALUES ('vienne');
INSERT INTO Ville(ville) VALUES ('vientiane');
INSERT INTO Ville(ville) VALUES ('washington');
INSERT INTO Ville(ville) VALUES ('wellington');
INSERT INTO Ville(ville) VALUES ('windhoek');
INSERT INTO Ville(ville) VALUES ('yaoundé');
INSERT INTO Ville(ville) VALUES ('zagreb');


-- -----------------------
-- ------- ADRESSE -------
-- -----------------------
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Saudi Arabia','70311','accra','Dolor Rd.',183);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Turkey','93176-484','windhoek','Malesuada Avenue',368);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Belize','45977','tokyo','Proin Avenue',331);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Belize','62189-425','copenhague','Nunc Av.',63);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Tonga','5700','bagdad','Convallis St.',205);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Mayotte','7606','tripoli','Ac Ave',123);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Germany','5631','brazzaville','Nec, St.',427);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Liberia','54595','madrid','Nunc St.',347);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Libya','40505','banjul','At Avenue',23);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Mauritania','1082','amsterdam','Montes Street',303);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Micronesia','39499','addis-abeba','Purus St.',241);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bulgaria','Y3H 7E7','berne','Nulla Ave',275);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brazil','41264','skopje','Dis Av.',120);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Faroe Islands','7099','phnom penh','Fringilla Ave',246);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Sri Lanka','51208','bandar','Purus. Rd.',69);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Sao Tome and Principe','71701','conakry','In St.',146);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('French Guiana','WI8 9UJ','budapest','Congue St.',294);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Martinique','9747','beyrouth','Porta Rd.',388);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Mexico','T95 4ZA','nicosie','A Street',80);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Latvia','NF99 0RV','bangui','Erat. Ave',426);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Panama','P47 2ZG','lisbonne','Purus, Rd.',240);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Uruguay','2426','oslo','Facilisis Avenue',51);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Jordan','02126','jakarta','Diam St.',185);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Greece','52567','montevideo','Id, St.',144);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Dominican Republic','0304HV','bamako','Elit Street',263);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Algerie','02163-214','alger','Nunc Av.',481);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Gambia','1435','panama','Lorem, St.',94);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Suriname','1112','dili','Accumsan Rd.',192);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Albania','89028','kinshasa','Dictum St.',135);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bonaire, Sint Eustatius and Saba','L2N 1Y3','tallinn','Ante Rd.',77);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Germany','68285-108','santiago','Mauris. St.',386);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Lesotho','67099','bangkok','Fames Ave',454);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Macedonia','3825','bruxelles','Vestibulum St.',435);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Guatemala','3592','saint-domingue','Sed Av.',92);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Denmark','R2 2PA','riyad','Viverra. Ave',338);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bouvet Island','97021','helsinki','Nec Avenue',110);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Pitcairn Islands','50901','la havane','Morbi Rd.',294);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Yemen','409097','berlin','A St.',26);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Liechtenstein','54556-541','nassau','Convallis Ave',456);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Mauritius','384668','andorre-la-vieille','Eget, Av.',11);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Antigua and Barbuda','X0P 8S3','nouakchott','Nec Ave',154);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Guam','81795','copenhague','Nulla Street',146);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Namibia','34432','guatemala','Vestibulum St.',304);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Uzbekistan','87539-172','bandar','Adipiscing Ave',366);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bahamas','7917','berne','Eleifend St.',53);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Kyrgyzstan','88926','san salvador','Arcu Ave',493);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Liechtenstein','7444','palikir','Vestibulum Avenue',294);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Grenada','35552','la paz','Rutrum Road',349);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75000','paris','Leo Av.',249);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','7500','paris','Cursus St.',85);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('United States','8215','luxembourg','In St.',434);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Saint BarthÃ©lemy','24790','islamabad','Non Rd.',429);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Montserrat','X4H 6K0','copenhague','Aliquet Rd.',461);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Gibraltar','27416-142','canberra','Cum Rd.',352);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Latvia','61507','khartoum','Felis St.',283);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Algeria','4104','san salvador','Id, Street',250);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Sweden','0261DC','nicosie','Parturient Avenue',39);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Djibouti','T6S 2A0','hamilton','Pellentesque Street',273);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Yemen','67301-291','montevideo',' Nulla. St.',121);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bhutan','38564','chisinau','Lorem. St.',467);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Lebanon','7373','bangkok','A, Ave',274);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Kiribati','62809','kiev','Nunc Rd.',358);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Viet Nam','1350','reykjavik','Consequat Avenue',481);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Liechtenstein','86427','san salvador','Et Avenue',409);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Mayotte','63866','bujumbura','Auctor. Av.',500);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Belarus','3578','minsk','Quis Avenue',473);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Solomon Islands','76105-775','honiara','Neque Avenue',472);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Bresil, State of','8490','brazzaville','Non St.',237);

INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75000','paris','Sophie Germain',249);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75012','paris','Roger Salengros',5);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75001','paris','Leo Av.',24);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75003','paris','Cursus St.',45);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75005','paris','Dubois',29);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75009','paris','Cursus St.',8);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75000','paris','Olympe Degouges',29);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75012','paris','Cursus St.',34);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75019','paris','Leo Av.',229);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75001','paris','Cursus St.',845);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75011','paris','Dupont.',23);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75002','paris','Cursus St.',7);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75005','paris','Victor Hugo',27);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75007','paris','Charles Baudelaire',75);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75008','paris','Robespierre',249);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75009','paris','Freud',85);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75010','paris','Raymond Point Rectangle.',249);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('France','75000','paris','Des Lilas',85);

INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Sophie Germain',29);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','nobou ganagashi',25);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','King Mao',234);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Mao tsé Tong',345);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Jutsu',2);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Nems',83);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Cesare',49);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Cursus St.',35);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Tsubasa',29);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','chidori',85);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Dupont.',3);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Cursus St.',7);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Victor Hugo',27);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','shogun avenue',75);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Robespierre',249);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Edo av',85);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Conan doyle',249);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Chine','100000','pékin','Des Lilas',85);

INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','Sophie Germain',7);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','nobou ganagashi',95);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','King Tsar',263);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','URSS',335);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','Vaudka',92);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','undercover',8);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','molotov',79);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','saint louis',45);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','ruskov',29);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','chidori',15);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','Dupont',8);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','Vladimir',97);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','staline',14);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Russie','101000','moscou','dostewosski',99);

INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Convallis St.',205);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Ac Ave',123);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Nec, St.',427);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Nunc St.',347);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','At Avenue',23);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Montes Street',303);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Purus St.',241);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Tortor Road',85);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Nulla Ave',275);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Dis Av.',120);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Fringilla Ave',246);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Purus. Rd.',69);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000', 'berlin','In St.',146);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Congue St.',294);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Porta Rd.',388);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','nicosie',80);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000', 'berlin','Erat. Ave',426);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000', 'berlin','lisbonne',240);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Allemagne','108000','berlin','Facilisis Avenue',51);


INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Convallis St.',205);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Ac Ave',123);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Nec, St.',427);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Nunc St.',347);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','At Avenue',23);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Purus St.',241);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Tortor Road',85);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Nulla Ave',275);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Dis Av.',120);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Fringilla Ave',246);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Purus. Rd.',69);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','In St.',146);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Congue St.',294);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Parturient Avenue',39);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Pellentesque Street',273);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro',' Nulla. St.',121);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Lorem. St.',467);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','A, Ave',274);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Nunc Rd.',358);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Auctor. Av.',500);
INSERT INTO Adresse (pays,cp,ville,rue,numero) VALUES ('Brésil','20000-000','rio de janeiro','Quis Avenue',473);



----------------------------
--------- PERSONNE ---------
----------------------------
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Finn','Knox','Finn.Knox@gmail.com',20);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Thaddeus','Christian','Thaddeus.Christian@hotmail.fr',31);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Alvin','Valentine','Alvin.Valentine@yahoo.fr',14);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Brynne','Price','Brynne.Price@gmail.com',48);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Barbara','Maxwell','Barbara@yahoo.fr',45);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Madison','Harmon','Madison.Harmon@gmail.com',58);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Malcolm','Sims','Malcolm.Sims@hotmail.fr',53);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Lawrence','Bean','Lawrence.Bean.et@yahoo.fr',35);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Margaret','Nielsen','Margaret.Nielsen@gmail.com',50);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('India','Moses','India.Moses@gmail.com',10);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Kyle','Rich','Kyle.Rich@hotmail.fr',14);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Venus','Cortez','Venus.Cortez@yahoo.fr',39);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Joshua','Patton','Joshua.Patton.nulla@gmail.com',9);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Caryn','Powers','Caryn.Powers@yahoo.fr',38);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Uta','Donovan','Uta.Donovan@hotmail.fr',35);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Amena','Kramer','Amena.Kramer@yahoo.fr',59);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Jena','Guthrie','Jena.Guthrie@gmail.com',54);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Isabelle','English','Isabelle.English@hotmail.fr',6);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Vladimir','Hodge','Vladimir.Hodge@yahoo.fr',26);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Andrew','Carey','Andrew.Carey@gmail.com',66);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Malcolm','Jenkins','Malcolm.Jenkins@hotmail.fr',42);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Yeo','Gibson','Yeo.Gibson@yahoo.fr',14);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Destiny','Petersen','Destiny.Petersen@yahoo.fr',9);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Bianca','Miranda','Bianca.Miranda@gmail.com',18);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Otto','Brown','Otto.Brown@hotmail.fr',50);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Connor','Bryan','Connor.Bryan@hotmail.fr',40);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Arden','Buckner','Arden.Buckner@yahoo.fr',59);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Ramona','Berg','Ramona.Berg@gmail.com',19);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Austin','Good','Austin.Good@yahoo.fr',39);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Ursula','Miller','Ursula.Miller@gmail.com',68);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Ava','Walter','Ava.Walter@yahoo.fr',21);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Kareem','Colon','Kareem.Colon@gmail.com',44);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Lana','Hoover','Lana.Hoover@hotmail.fr',6);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Brianna','Crosby','Brianna.Crosby.parturient@gmail.com',34);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Sheila','Gomez','Sheila@hotmail.fr',53);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Curran','Fischer','Curran@gmail.com',45);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Petra','Roach','Petra@hotmail.fr',37);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Matthew','Cherry','Matthew.Cherry@yahoo.fr',11);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Inez','Dunn','Inez.Dunn.lectus@hotmail.fr',3);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Fuller','Hendricks','Fuller.Hendricks.quam@yahoo.fr',7);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Odysseus','Mcclain','Odysseus.Mcclain.Duis@gmail.com',37);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Bree','Dale','Bree@hotmail.fr',7);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Rina','Ross','Rina@hotmail.fr',1);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Aretha','Justice','Aretha@gmail.com',30);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Sybill','Reyes','Sybill.Reyes.vulputate@yahoo.fr',17);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Mia','Saunders','Mia@hotmail.fr',5);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Simon','Chambers','Simon.Chambers@yahoo.fr',59);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Myra','Gallegos','Myra@gmail.com',59);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Bianca','Pearson','Bianca.Pearson@hotmail.fr',13);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Amy','Bean','Amy.Bean@yahoo.fr',38);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Channing','King','Channing.King@gmail.com',66);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Nita','Mcbride','Nita.Mcbride@hotmail.fr',50);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Leigh','Ortiz','Leigh.Ortiz@ipsum@gmail.com',43);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Isaiah','Mclaughlin','Isaiah@hotmail.fr',42);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Adrienne','Miller','Adrienne.Miller@hotmail.fr',63);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Yuli','Eaton','Yuli.Eaton.nonummy@hotmail.fr',57);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Yuri','Norman','Yuri.Norman@gmail.com',16);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Judith','Vaughan','Judith.Vaughan@gmail.com',12);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Quinn','Haney','Quinn.Haney@hotmail.fr',10);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Dante','Knapp','Dante.Knapp@yahoo.fr',46);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Lewis','Ward','Lewis.Ward.orci@gmail.com',57);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Denise','Reid','Denise.Reid.yahoo.fr',48);
INSERT INTO Personne (nom,prenom,mail,idAdresse) VALUES ('Abra','Bates','Abra.Bates@yahoo.fr',28);


---------------------
------ COMPTE -------
---------------------
INSERT INTO Compte (login,password,idPersonne) VALUES ('Reuben','NUQ17DUN3KZ',63);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Kevyn','KQD23DQV4RS',25);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Yardley','ZVZ79ZPJ7WG',37);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Keith','BTV62GEF0ND',16);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Hayley','AJY17QWF7TW',21);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Jonas','AIP06DAV4HO',15);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Chastity','MMK15IMF1RZ',1);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Stacy','GFA86BMS9NJ',44);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Janna','KAZ74SPH7LP',28);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Ciara','UOU67QCG1CZ',20);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Yoshio','NRN22LLO3HH',17);
INSERT INTO Compte (login,password,idPersonne) VALUES ('Laith','ENA75TPK3TB',2);



----------------------
------ LOGEMENT ------
----------------------
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',458,1,816,1);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',713,7,1087,2);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',202,5,1003,3);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',275,8,309,4);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',68,6,640,5);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',21,9,577,6);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',194,9,3258,7);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',417,6,3068,8);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',45,2,100,9);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',319,4,312,10);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',15,2,472,11);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',97,10,294,12);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Chambre',456,4,5141,13);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',377,6,8957,14);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',406,3,903,16);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',86,4,90,18);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',126,9,2241,19);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',513,10,149,20);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',649,2,49,21);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',451,6,3432,22);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',93,7,44,23);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',32,7,593,24);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',6,1,100,25);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Chambre',85,5,506,26);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',449,3,65,27);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',78,4,147,28);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',330,8,8269,29);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',66,1,225,30);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',17,2,4340,31);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',40,6,730,32);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',358,4,6785,33);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',94,3,5042,34);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',256,5,781,35);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',164,1,6900,36);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',18,2,9395,37);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',583,1,63622,38);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',252,4,5402,39);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',92,3,1354,40);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',397,8,498,89);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',86,9,1727,90);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',69,9,720,91);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Chambre',83,4,9149,92);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',85,1,6793,93);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',69,5,2082,94);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',93,4,3001,95);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',20,5,9531, 96);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',19,8,1902,97);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',233,8,634,98);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',95,4,285,99);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',91,1,231,100);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',23,2,825,101);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',31,10,169,102);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',47,4,803,103);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',46,8,898,104);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',12,4,966,105);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',65,3,96,106);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',94,7,761,59);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',95,1,100,60);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',556,8,381,61);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',63,9,285,62);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',57,1,162,63);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',85,8,27,64);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',518,7,53,65);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',402,8,367,66);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',36,3,561,68);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',671,6,840,69);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',604,4,161,71);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',97,4,903,72);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',436,8,298,73);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',132,4,926,74);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',63,3,76,75);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',94,7,761,76);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',95,1,469,77);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',56,8,381,78);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',63,9,225,79);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',57,1,362,80);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',865,8,237,81);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',51,7,55,82);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',42,8,37,83);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',36,3,57,84);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',671,6,80,85);

INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',115,2,72,106);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',987,10,94,107);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Chambre',456,4,51,108);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',37,6,87,109);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',46,3,93,110);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',96,1,90,111);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',126,9,21,112);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',513,10,349,113);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',649,2,69,114);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',451,6,342,115);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',93,7,3144,116);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',1000,7,8593,117);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',636,1,7315,118);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Chambre',835,5,506,119);

INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',44,3,665,120);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',78,4,1747,121);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',30,8,869,122);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',676,1,5225,123);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',87,2,440,124);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',40,6,730,125);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',17,2,4340,126);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',40,6,730,127);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',58,4,6785,128);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',94,3,5042,129);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',256,5,3781,130);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',14,1,6900,131);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',18,2,95,132);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',583,12,6622,133);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',252,4,52,134);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',72,3,4,135);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',37,8,8,136);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',98,9,7,137);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',69,9,2,138);

INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Appartement',47,4,803,139);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour sans amis','Appartement',18,2,95,140);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique','Appartement',18,2,95,141);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',65,3,96,142);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',94,7,761,143);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Situe en plein centre ville','Appartement',95,1,100,144);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Appartement',556,8,381,145);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',63,9,285,146);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',57,1,162,147);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Chambre',85,8,27,148);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Chambre',518,7,53,149);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',402,8,367,150);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Studio de charme','Appartement',36,3,561,151);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',87,2,440,152);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',40,6,730,153);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Pour un sejour romantique ou familial','Chambre',17,2,4340,154);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Le studio beneficie d une entree independante','Appartement',40,6,730,155);
INSERT INTO Logement (description,type,surface,nb_pieces,prix,idAdresse) VALUES ('Appartement propre et bien meuble','Chambre',58,4,6785,156);



-- -----------------------
-- ------- PRESTATIONS ---
-- -----------------------

INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,8);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('poterie',15,10);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,23);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('piscine',15,27);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('randonnee',15,29);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,29);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,35);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('zoo',15,35);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('2',43,36);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,37);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('poterie',15,37);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,47);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('piscine',15,47);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('randonnee',15,48);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,49);;
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('1',15,52);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,53);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('1',15,3);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,54);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,55);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('zoo',15,56);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('2',43,56);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,57);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('poterie',15,63);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,67);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('piscine',15,69);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('randonnee',15,72);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,80);


INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('0',13,86);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('2',43,86);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,87);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('tennis',53,88);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,89);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('zoo',15,90);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('1',15,91);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',15,91);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('randonnee',15,92);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('1',15,92);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,93);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('1',15,93);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,94);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,95);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('zoo',15,96);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('2',43,96);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,97);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('poterie',15,97);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,97);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('piscine',15,97);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('randonnee',15,98);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,99);

INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('0',13,100);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('2',43,100);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,102);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('tennis',53,103);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,104);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('kremelin',15,108);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('1',15,108);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',15,110);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('randonnee',15,113);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('kremelin',13,113);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('2',43,114);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',33,120);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('tennis',53,120);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('golf',15,120);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('zoo',15,122);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('1',15,122);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('3',15,124);
INSERT INTO Prestation (prestation, prix, idLogement) VALUES ('randonnee',15,130);


-----------------
--- Transport ---
-----------------

INSERT INTO Transport(ville, nb_vehicule_libre, prix) VALUES
('paris', 10, 40),
('pékin', 100, 15),
('moscou', 5, 150);
